export enum DropdownType {
    ChargeAmountTo = 1,
    Designation = 2,
    FuelCategory = 3,
    Gender = 4,
    CivilStatus = 5,
    Relationship = 6,
    EmployeeStatus = 7,
    CustomerStatus = 8,
    TaxCode = 9,
    VehicleMakeAndModel = 10,
    VehicleStatus = 11,
    TankStatus = 12,
    ReasonToFuelPriceChange = 13,
    Provice = 14,
    City = 15,
    Barangay = 16,
    DiscountCriteria = 16,
    DiscountType = 17,
    SubDepartment = 18
}